version: '3'
services:
  python3:
    build: .
    container_name: 'python3'
    working_dir: '/app'
    tty: true
    environment:
      - GCP_KEY_PATH=/app/youtube-data-api-385206-c3a94f0b7c7c.json
    volumes:
      - type: bind
        source: '.'
        target: '/app'
  web:
    image: apache/airflow:2.0.0
    container_name: airflow
    ports:
      - 8080:8080
    volumes:
      - ./opt/airflow:/opt/airflow
    # command: db init
    # command: webserver
    command: >
      bash -c "airflow webserver -p 8080 -D && airflow scheduler -D"