name: Authenticate to Google Cloud
description: "Authenticate Google Cloud"

inputs:
  workload_identity_provider:
    description: "workload_identity_provider id"
    required: true
  service_account:
    description: "service account email address"
    required: true
outputs:
  gcloud_token:
    description: "The GCP access token"
    value: ${{ steps.auth.outputs.access_token }}


runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        project_id: ${{ env.PROJECT_ID }}
        output_token: true

    - id: 'setup-to-google-cloud'
      name: 'Setup Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
