name: Authenticate to Google Cloud
description: "Authenticate Google Cloud"

inputs:
  workload_identity_provider:
    description: "workload_identity_provider id"
    required: true
  service_account:
    description: "service account email address"
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        project_id: ${{ env.PROJECT_ID }}

    - id: 'setup-to-google-cloud'
      name: 'Setup Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    # トークンを取得して出力
    - name: Get Google Cloud Token
      id: get-token
      shell: bash
      run: echo "gcloud_token=$(gcloud auth print-identity-token)" >> $GITHUB_OUTPUT