name: Authenticate to Google Cloud
description: "Authenticate Google Cloud"

inputs:
  workload_identity_provider:
    description: "workload_identity_provider id"
    required: true
  service_account:
    description: "service account email address"
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        project_id: ${{ env.PROJECT_ID }}