name: Setup Before Terraform Plan & Apply
description: "Setup Before Terraform Plan & Apply"

inputs:
  workspace:
    description: terraform workspace name
    required: true
  working-directory:
    description: terraform command execute directory
    required: true

outputs:
  fmt_outcome:
    description: terraform fmt result
    value: ${{ steps.fmt.outcome }}
  init_outcome:
    description: terraform init result
    value: ${{ steps.init.outcome }}
  validate_outcome:
    description: terraform validate result
    value: ${{ steps.validate.outcome }}
  validate_output:
    description: terraform validate output content
    value: ${{ steps.validate.outputs.stdout }}

runs:
  using: "composite"
  steps:
      # https://github.com/hashicorp/setup-terraform
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        id: init
        run: terraform init

      - name: Terraform Validate
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        id: validate
        run: terraform validate -no-color

      - name: Terraform Workspace Select
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}