# ベースイメージの指定（ビルドステージ）
FROM python:3.11.7-slim AS builder

ENV APP_HOME=/app
WORKDIR $APP_HOME

# pipとpoetryのインストール
RUN pip install --upgrade pip && pip install poetry
# poetry-plugin-exportのインストール
RUN poetry self add poetry-plugin-export

# poetryの依存関係をコピー
COPY ./pyproject.toml ./poetry.lock ./

# 依存関係のインストール
RUN poetry export --without-hashes --with dev -f requirements.txt > requirements-dev.txt
RUN pip install -r requirements-dev.txt

# 開発環境の設定
FROM python:3.11.7-slim as dev
ENV PYTHONUNBUFFERED=1
ENV APP_HOME=/app
WORKDIR $APP_HOME

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin/ /usr/local/bin/

COPY ./ ./

# アプリケーションの実行
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081", "--reload"]
